name: Deploy to cPanel

on:
 push:
  branches:
    - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
  - name: Install lftp
    run: sudo apt install lftp

  - name: Configure lftp
    run: |
      mkdir ~/.lftp
      echo "set ssl:verify-certificate false;" >> ~/.lftp/rc

  - name: Load Secrets
    run: |
      echo "machine ${{ secrets.FTP_SERVER }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc

  - name: Upload contents
    run: |
      lftp -e "mirror --only-newer --parallel=100 -R . /links.shubhamlal.in/" ${{ secrets.FTP_SERVER }}