name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Install lftp
      run: sudo apt install lftp

    - name: Configure lftp
      run: |
        mkdir ~/.lftp
        echo "set ssl:verify-certificate false;" >> ~/.lftp/rc

    - name: Load Secrets
      run: |
        echo "machine ${{ secrets.FTP_SERVER }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc

    - name: Change to project directory
      run: cd $GITHUB_WORKSPACE

    - name: Install dependencies and build frontend
      run: |
        npm install
        npm run build

    - name: Upload contents
      run: |
        lftp -e "mirror --only-newer --parallel=100 -R ./dist/ /links.shubhamlal.in/" ${{ secrets.FTP_SERVER }}